<?php include 'config/config.php'; ?>

<?php 
// Load banners from DB for carousel
$bannerQuery = "SELECT banner_id, banner_image, description FROM banners ORDER BY banner_id ASC LIMIT 3";
$bannerResult = mysqli_query($conn, $bannerQuery);
$banners = [];
while ($row = mysqli_fetch_assoc($bannerResult)) {
    $banners[] = $row;
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
    <link rel="stylesheet" href="style/Homepage_style.css">
    <link rel="stylesheet" href="style/main.css">
</head>

<body>
    <?php include 'komponen/navbar.php'; ?>
    <main>
        <!-- SLIDER -->
        <div class="carousel-container">
            <div class="carousel">
                <?php if (!empty($banners)): ?>
                    <?php foreach ($banners as $banner): 
                        $imgSrc = 'data:image/jpeg;base64,' . base64_encode($banner['banner_image']);
                        $desc = htmlspecialchars($banner['description']);
                    ?>
                        <div class="slide">
                            <img src="<?= $imgSrc ?>" alt="Banner <?= $banner['banner_id'] ?>" />
                            <div class="slide-content">
                                <p><?= $desc ?></p>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div class="slide">
                        <p>No banners configured yet.</p>
                    </div>
                <?php endif; ?>
            </div>

            <div class="carousel-nav">
                <div class="nav-dot active" data-index="0"></div>
                <div class="nav-dot" data-index="1"></div>
                <div class="nav-dot" data-index="2"></div>
            </div>
        </div>
    </main>
</body>
</html>


    <!-- EVENT CARDS -->
    <div class="events-section">
        <h2 class="events-title">Mungkin Anda Akan Tertarik Dengan Ini!</h2>
        
        <div class="event-cards-wrapper">
            <div class="event-cards-container" id="eventCardsContainer">
                <?php
                // Query untuk mendapatkan SEMUA event
                $eventQuery = "SELECT e.*, t.harga_tiket, t.stok_tiket, t.id_tiket
                            FROM event e
                            LEFT JOIN tiket t ON e.id_event = t.id_event
                            GROUP BY e.id_event
                            ORDER BY e.tanggal_event ASC";
                $eventResult = mysqli_query($conn, $eventQuery);

                // Ambil semua data event ke dalam array
                $allEvents = [];
                while ($event = mysqli_fetch_assoc($eventResult)) {
                    $allEvents[] = $event;
                }

                // Output event cards dengan data attribute untuk JavaScript
                foreach ($allEvents as $index => $event) {
                    $poster = base64_encode($event['poster_event']);
                    $posterSrc = "data:image/jpeg;base64," . $poster;
                    $tanggal = date("d M Y", strtotime($event['tanggal_event']));
                    $harga = number_format($event['harga_tiket'], 0, ',', '.');
                    $stok = $event['stok_tiket'];

                    echo '<div class="event-card" data-card-index="' . $index . '">
                        <div class="event-image" style="background-image: url(\'' . $posterSrc . '\')"></div>
                        <div class="event-details">
                            <div class="event-name">' . htmlspecialchars($event['nama_event']) . '</div>
                            <div class="event-date">' . $tanggal . '</div>
                            <div class="event-price">Rp' . $harga . '</div>';
                    if ($stok > 0) {
                        echo '<a href="Deskripsi_tiket.php?id_event=' . $event['id_event'] . '" class="event-button">LIHAT</a>';
                    } else {
                        echo '<a href="#" class="empty-event-button">Stok Tidak Tersedia</a>';
                    }
                    echo '</div></div>';
                }
                ?>
            </div>
        </div>
        
        <!-- Pagination Controls -->
        <div class="pagination-container" id="paginationContainer" style="display: none;">
            <button class="pagination-btn prev-btn" id="prevBtn">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <polyline points="15,18 9,12 15,6"></polyline>
                </svg>
            </button>
            <div class="pagination-numbers" id="paginationNumbers">
                <!-- Generated by JavaScript -->
            </div>
            <button class="pagination-btn next-btn" id="nextBtn">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <polyline points="9,18 15,12 9,6"></polyline>
                </svg>
            </button>
        </div>
    </div>
    </main>

    <div class="footer">
        <p>&copy; 2025 EVENTLY. All Rights Reserved.</p>
        <ul class="footer-links">
            <li><a href="#">Contact-Admin</a></li>
        </ul>
    </div>
    <script src="Homepage_script.js"></script>
</body>

</html>